### ISSUE TITLE
Convenient way to export breadcrumbs as a collection

### ISSUE THREAD

**Issue by innocenzi** [glhd/gretel#1]
I'm looking for a solution to handle breadcrumbs for an application written with Inertia. This package seems like a good candidate, I like the syntax macro'd to the routes. 

My issue is that this package was made with Blade in mind, thus it doesn't offer a convenient way to export the breadcrumbs as a collection. I need this feature because with Inertia, you pass whatever the front-end need to a middleware, and work with it in the front-end. 

My current workaround is the following: 

```php
// Middleware/ShareNavigation.php
public function handle($request, \Closure $next)
{
    inertia()->share('navigation', [
        'breadcrumbs' => app(\Glhd\Gretel\View\Components\Breadcrumbs)->breadcrumbs,
        // other stuff
    ]);

    return $next($request);
}
```

A facade would be better:

```php
Breadcrumbs::render();
// or something like
Breadcrumbs::asCollection();
```

**Comment by innocenzi** [comment]
I think both options for different use cases would be nice, but in my current case I just need the behavior of the described workaround, so I think that means "just the current route". For instance:

```php
Route::get('/users/{user}/edit', [Administration\Controllers\UsersController::class, 'edit'])
    ->withTrashed()
    ->name('users.edit')
    ->breadcrumb(fn (User $user) => $user->full_name, 'admin.users');
```

In this case, I get two parts: one with `is_current_page` set to `true` and with a title corresponding to `$user->full_name`, and the parent corresponding to the named route `admin.users`.

**Comment by inxilpro** [comment]
Take a look at [1.3.0](https://github.com/glhd/gretel/releases/tag/1.3.0) and feel free to reopen this issue if that doesn't cover your use case.

**Comment by innocenzi** [comment]
Dude, this is way better than my expectations. Thanks a lot!
