### ISSUE TITLE
Rouote::resource - parents ? 

### ISSUE THREAD

**Issue by rasasak** [glhd/gretel#13]
Is there any way to add parent to resource route ? 
I try second argument like: 

Route::resource('users', UserController::class)
  ->breadcrumbs([
    'index' => 'Users',
    'create' => 'New User',
    'show' => fn(User $user) => $user->name,
    'edit' => 'Edit',
  ], 'dashhboard');

but it is not working ...

**Comment by inxilpro** [comment]
You'll need to use the callback syntax to do this. Try this:

```php
Route::resource('users', UserController::class)
  ->breadcrumbs(
    fn($breadcrumbs) => $breadcrumbs
      ->index('Users', 'dashboard')
      ->create('New User')
      ->show(fn(User $user) => $user->name)
      ->edit('Edit')
  );
```

This will set the `dashboard` route as the parent of `users.index` but leave all the other implicit parents set (eg. `users.index` is the parent of `users.show`). If you want **all** the routes to be children of `dashboard`, just set the second parameter to `'dashboard'` in each method call.
