### ISSUE TITLE
Breadcrumbs return an empty array for Resource routes

### ISSUE THREAD

**Issue by MrThePlague** [glhd/gretel#4]
**Describe the bug**
Using the `breadcrumbs()` method on a Resource route returns an empty array with either the Array or Callback syntax.

**What version does this affect?**
 - Laravel Version: 8.73.2
 - Package Version: 1.4.0
 - Inertia.js Version: 0.4.5

**To Reproduce**
Here is an example of a resource route in my `web.php` routes file, although I've also tried the Callback syntax:

```php
Route::resource('/model, App\Http\Controllers\Web\Model\ModelController::class)
    ->names('web.models')
    ->breadcrumbs([
        'index' => 'Model',
        'create' => 'New Model',
        'show' => fn (\App\Models\Model $model) => $model->name,
        'edit' => 'Edit',
      ]);
```

**Expected behavior**
Dumping `$request->route()->breadcrumbs()->jsonSerialize()` should return an Array of the breadcrumbs; however, it returns an empty Array.

**Additional context**

**Comment by inxilpro** [comment]
Oops, sorry! Somehow I missed this. I'll take a look shortly.

**Comment by inxilpro** [comment]
@MrThePlague in what context are you accessing the `$request`? I just checked our test suite, and this seems to work just fine:

```php
Route::resource('users', ResourceRoutesTestController::class)
  ->breadcrumbs([
    'index' => 'Users',
    'create' => 'New User',
    'show' => fn(User $user) => $user->name,
    'edit' => 'Edit',
  ]);

$this->get(route('users.index'));

dd(request()->route()->breadcrumbs()->jsonSerialize());
```

Dumps:

```
array:1 [
  0 => array:3 [
    "title" => "Users"
    "url" => "http://localhost/users"
    "is_current_page" => true
  ]
]
```

**Comment by MrThePlague** [comment]
I think I tracked down the issue to my use of the https://github.com/archtechx package, so sorry about this!

**Comment by hexlay** [comment]
I have exact same issue however i don't use Tenancy or anything similar. Just grouped the route.
Stack is also the same: **Laravel 10 + Inertia 1.0 + Gretel 1.7**

```
Route::prefix('admin')->as('admin.')->group(function () {
        Route::resource('/users', UsersController::class)
            ->except('show')
            ->breadcrumbs(function (ResourceBreadcrumbs $breadcrumbs) {
                $breadcrumbs
                    ->index('Users', 'dashboard')
                    ->create('New User')
                    ->edit('Update Role');
            });
    });
```

HandleInertiaRequests looks like this:
```
public function share(Request $request): array
    {
        return array_merge(parent::share($request), [
            'app' => [
                'breadcrumbs' => $request->route()->breadcrumbs()->jsonSerialize(),
            ],
            'ziggy' => function () use ($request) {
                return array_merge((new Ziggy)->toArray(), [
                    'location' => $request->url(),
                ]);
            },
        ]);
    }
```

If i **dd** **$request->route()->breadcrumbs()->jsonSerialize()** response is always null
