### ISSUE TITLE
Easily add breadcrumbs to routes of packages without overriding them

### ISSUE THREAD

**Issue by ThaDaVos** [glhd/gretel#8]
**Is your feature request related to a problem? Please describe.**
Current I am using Laravel Jetstream in my application, this package registers a lot of default routes - currently I haven't foùnd an easy way, except overriding the full route, to add breadcrumbs to these...
**Describe the solution you'd like**

An easy way to add breadcrumbs to routes not in your control without the need of overiding them, something like:

```PHP
Gretel::breadcrumb('{ROUTE_NAME}', ....{NORMAL GRETEL PARAMS});
// OR
Gretel::breadcrumb('{ROUTE_URI}', ....{NORMAL GRETEL PARAMS});
```

**Describe alternatives you've considered**

Overriding the full route to add the breadcrumb

**Additional context**

**Comment by ThaDaVos** [comment]
Just like this one supports:
https://github.com/diglactic/laravel-breadcrumbs

**Comment by inxilpro** [comment]
Yeah, that makes a lot of sense. It should be fairly easy to add something like:

```php
Gretel::custom(
  route: 'teams.show',
  title: fn(Team $team) => $team->name,
  parent: 'profile.show',
  parameters: ['team'],
);
```

The only thing that kinda sucks is that Gretel needs to know the route's parameter names in advance, so you'd have to pass them in. I'm trying to think if there's a way to get around that…

**Comment by inxilpro** [comment]
@ThaDaVos I just pushed a feature to `@glhd/gretel:dev-main` that should do the trick. You can just call `Gretel::breadcrumb()` with the same arguments as normal, but with the route name as an extra first argument.

```php
Gretel::breadcrumb(
  route: 'teams.show',
  title: fn(Team $team) => $team->name,
  parent: 'profile.show',
);
```

If you have a chance to try it and confirm it works for your use-case, that'd be great. I'll do some testing later this week and release it.

**Comment by ThaDaVos** [comment]
Great! I'll take a look when I have the time - I have changed my local implementation though so I was able to auto-generate a `routes/breadcrumbs.php` file (I was a bit lazy)
